/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Ai: () => import('#controllers/ai_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Customer: () => import('#controllers/customer_controller'),
  Document: () => import('#controllers/document_controller'),
  Group: () => import('#controllers/group_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  User: () => import('#controllers/user_controller'),
}
