/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstName', 'id', 'isFarmCreated', 'lastName', 'phoneNumber', 'updatedAt', 'userId', 'username', 'uuid'] as const
  $columns = CustomerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isFarmCreated: boolean | null
  @column()
  declare lastName: string
  @column()
  declare phoneNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare username: string | null
  @column()
  declare uuid: string
}

export class DocumentContentFileSchema extends BaseModel {
  static $columns = ['createdAt', 'documentId', 'extension', 'id', 'name', 'realName', 'size', 'type', 'updatedAt', 'uuid'] as const
  $columns = DocumentContentFileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare documentId: number | null
  @column()
  declare extension: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare realName: string | null
  @column()
  declare size: number | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class DocumentSchema extends BaseModel {
  static $columns = ['content', 'contentJson', 'contentMarkdown', 'createdAt', 'customerId', 'description', 'editorType', 'groupId', 'id', 'tags', 'thumbnail', 'title', 'updatedAt', 'userId', 'uuid'] as const
  $columns = DocumentSchema.$columns
  @column()
  declare content: string | null
  @column()
  declare contentJson: any | null
  @column()
  declare contentMarkdown: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerId: number | null
  @column()
  declare description: string | null
  @column()
  declare editorType: string | null
  @column()
  declare groupId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tags: string | null
  @column()
  declare thumbnail: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare uuid: string
}

export class GroupSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'description', 'id', 'name', 'tags', 'updatedAt', 'userId', 'uuid'] as const
  $columns = GroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerId: number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare tags: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare uuid: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'type', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstName', 'id', 'isBanned', 'isEmailVerified', 'isOnboardingComplete', 'isPhoneNumberVerified', 'lastName', 'onboardingAnswers', 'password', 'phoneNumber', 'roleId', 'signinCode', 'signinCodeExpiresAt', 'updatedAt', 'username', 'uuid'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isBanned: boolean | null
  @column()
  declare isEmailVerified: boolean | null
  @column()
  declare isOnboardingComplete: boolean | null
  @column()
  declare isPhoneNumberVerified: boolean | null
  @column()
  declare lastName: string
  @column()
  declare onboardingAnswers: any | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phoneNumber: string | null
  @column()
  declare roleId: number
  @column()
  declare signinCode: string | null
  @column.dateTime()
  declare signinCodeExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
  @column()
  declare uuid: string
}
